[Feature/#9] 대시보드 페이지 퍼블리싱
The-Monitor-Dev/The-Monitor-FE pull request #23
Opened 2024-10-20 16:34 UTC by Sohyunnnn

## 💻 관련 이슈

- close #9 

## 💡 작업내용

- 대시보드 페이지 퍼블리싱
- 미트볼 클릭 시 메뉴 모달 퍼블리싱
- 삭제 모달 퍼블리싱

## 🧐 참고 사항

-

## 🖼️ 스크린샷

https://github.com/user-attachments/assets/d8f4be40-351e-4c96-bc88-7adcd59b3e9b

## ️✅ 체크리스트 (PR 올리기 전 아래 내용을 확인해 주세요)

- [ ] Reviewers를 지정해주세요
- [ ] Assignees는 본인을 선택해주세요
- [ ] label을 선택해주세요

2024-10-20 16:44 UTC, Sohyunnnn commented
[질문] 
<button> cannot appear as a descendant of <button>.
이런 warning 뜨는데 큰 버튼을 수정할 필요가 있는지 아니면 둘 다 버튼이 맞기 때문에 버튼 태그로 두는 게 맞는지 궁금합니다,,,

2024-10-20 16:46 UTC, Sohyunnnn commented
[질문] CloseIcon과 같은 Icon도 type=button 지정해주는 게 좋나요? 
(CloseIcon 클릭 시 모달이 닫히는 로직)

2024-10-21 07:29 UTC, tacowasabii commented
> [질문] CloseIcon과 같은 Icon도 type=button 지정해주는 게 좋나요? (CloseIcon 클릭 시 모달이 닫히는 로직)

그동안 안했었는데 해주면 좋을거 같습니다. 근데 cursor-pointer도 같이 해줘야 해요

2024-10-25 09:46 UTC, tacowasabii requested changes

2024-10-25 09:46 UTC, tacowasabii commented on src/pages/Dashboard/components/DeleteModal/index.tsx
> +  };
[질문] 이거 없이 그냥 onClose 그대로 넣어도 되는데 확장성땜에 이렇게 만든건가요?

2024-10-25 09:46 UTC, tacowasabii commented on src/pages/Dashboard/index.tsx
> +  const [isActive, setIsActive] = useState(false);
[제안] 이거 그냥 isMenuOpen 하나로만 관리해도 되지 않을까요?

2024-10-25 09:46 UTC, tacowasabii commented on src/pages/Dashboard/index.tsx
> +        </div>
```suggestion
        <button className="flex w-full group-hover:bg-neutral-100">
          <img src={DefaultImage} className="m-4 w-24 rounded" />
          <div className="flex w-full flex-col gap-1 py-5 pl-4 pr-5">
            <h2 className="text-left text-2xl font-semibold text-title">
              한솥
            </h2>
            <div className="flex items-center">
              <PersonIcon className="mr-1" />
              <p className="mr-2 text-md font-regular text-body3">담당자</p>
              <p className="text-md font-semibold text-body1">이현수</p>
            </div>
          </div>
        </button>
```
[변경 요청] 말씀하신 에러는 버튼안에 버튼을 또 만들어서 나는 에러라서 상위 버튼 없애고 이렇게 바꾸면 될거 같습니다. 제가 이전에 전체를 버튼으로 만들면 된다했던거는 안에 버튼이 또 있다는걸 인지하지 못했었고, 오른쪽 케밥 아이콘이 있는 영역은 눌리지 않아도 괜찮을거 같습니다

2024-10-26 12:35 UTC, Sohyunnnn commented on src/pages/Dashboard/components/DeleteModal/index.tsx
> +  };
네 맞습니다. 추후 필요없다고 판단되면 없애겠습니다!

2024-10-26 12:39 UTC, Sohyunnnn commented on src/pages/Dashboard/index.tsx
> +  const [isActive, setIsActive] = useState(false);
코드 수정했습니다. 감사합니다!

2024-10-26 13:10 UTC, tacowasabii approved these changes
수고하셨습니다

2024-10-26 13:14 UTC, merged