[Feature/#24] 고객사 정보 추가 모달 구현
The-Monitor-Dev/The-Monitor-FE pull request #25
Opened 2024-10-22 17:26 UTC by Sohyunnnn

## 💻 관련 이슈

- close #24 

## 💡 작업내용

- 고객사 정보 추가 모달 퍼블리싱
- 일부 기능 구현

## 🧐 참고 사항

- 퍼블리싱만 했을 때에도 코드가 너무 길어져서 회원가입처럼 컴포넌트화를 하는 게 좋을 지 이대로 가는 게 좋을 지 조언 바랍니다.
- 코드 계속 가지고 있기 좀 그래서 pr 올린 점 양해 부탁드립니다. 순차적으로 리뷰 남겨주시면 문제점 보완하겠습니다. 해당 pr은 코드 리뷰 완료 후 리팩토링 및 디테일한 작업 이루어질 예정입니다.(에러 처리, 버튼 비활성화 등)
- 하단 이미지와 같은 모달 다른 페이지에서도 텍스트만 다르고 디자인은 똑같이 쓰이는데 컴포넌트화 하면 좋을 지 의견 부탁 드립니다.
<img width="255" alt="image" src="https://github.com/user-attachments/assets/9ed05caa-ac03-44fa-a998-e02b55bb0286"> <br />
- 회원가입 및 일부 페이지에서 메일 주소가 달라진 것 확인하여, 코드 수정한 점 참고 부탁드립니다.

## 🖼️ 스크린샷

https://github.com/user-attachments/assets/61c2161b-407a-4714-a207-49593ed6632a

## ️✅ 체크리스트 (PR 올리기 전 아래 내용을 확인해 주세요)

- [ ] Reviewers를 지정해주세요
- [ ] Assignees는 본인을 선택해주세요
- [ ] label을 선택해주세요

2024-10-26 03:30 UTC, tacowasabii requested changes
1. AddModal 코드가 너무 길어서 회원가입 처럼 단계별로 컴포넌트 분리해주세요. 이후에 코드 다시 확인하겠습니다.
2. 현재 몇스텝인지 알려주는 오른쪽 상단의 동그라미 아이콘이 빠져있습니다.
3. 회원가입처럼 단계별로 넘어갈때 슬라이드 애니메이션을 주는게 어떨까요? 구현은 회원가입 참고하시면 어렵지 않게 적용할 수 있을거예요
4. 디자인 확인해보니 첨부한 이미지 디자인이 말씀하신대로 계속 쓰여서 컴포넌트화하면 좋을거 같습니다.

2024-11-03 06:30 UTC, tacowasabii requested changes
수고하셨습니다. 전체적으로 잘 만드셨네요. 자잘한거 수정 및 고객사 정보 수정 모달 위치만 바꾸면 될거 같습니다.
근데 고객사 정보 수정 모달은 언제 뜨나요? 로직이 안들어가있는거 같네요

2024-11-03 06:30 UTC, tacowasabii commented on src/pages/Dashboard/components/AddModal/Step1/index.tsx
> +  const [uploadImg, setuploadImg] = useState<string | null>(null);
[제안] 이름 명사형으로 바꿔주시고 카멜케이스 유의해주세요

2024-11-03 06:30 UTC, tacowasabii commented on src/pages/Dashboard/components/AddModal/Step3/index.tsx
> +        데일리모니터링을 위한 키워드를 설정해주세요
[변경 요청] 이거 잘못 돼있는거 같네요

2024-11-03 06:30 UTC, tacowasabii commented on src/pages/Dashboard/components/AddModal/Step4/index.tsx
> +const Step4 = () => {
[변경 요청] AddModal이 아니라 EditModal로 옮기는게 맞는거 같습니다

2024-11-03 06:30 UTC, tacowasabii commented on src/pages/Dashboard/components/AddModal/Step4/index.tsx
> +  const [uploadImg, setuploadImg] = useState<string | null>(null);
[제안] 여기도 동일합니다

2024-11-03 06:30 UTC, tacowasabii commented on src/pages/Dashboard/components/AddModal/Step4/index.tsx
여기 아마 api 연결하면 이미지 보여주는 로직 바꿔야 할거에요

2024-11-03 06:30 UTC, tacowasabii commented on src/pages/Dashboard/components/AddModal/index.tsx
> +        {step !== 1 && step !== 4 && (
[변경 요청] step4를 여기서 고려할 필요는 없어보입니다

2024-11-03 09:16 UTC, Sohyunnnn commented on src/pages/Dashboard/components/AddModal/Step4/index.tsx
step4 관련은 로직을 착각하였고, 추후 issue 업로드 후 관련 모달 및 로직 수정 예정입니다.

2024-11-03 09:21 UTC, tacowasabii approved these changes

2024-11-03 09:21 UTC, merged